### ISSUE TITLE
Cookbook self-dependency cleanup checklist

### ISSUE THREAD

**Issue by lamont-granquist** [chef/supermarket#1046]
- [x] filter outgoing /universe endpoint to not render self-dependencies
- [ ] filter outgoing cookbook_versions to not render self-dependencies
- [x] filter incoming cookbook uploads so that stored metadata will not have self-dependencies
- [ ] add database migration to strip existing self-dependencies out of cookbooks

**Comment by lamont-granquist** [comment]
The universe endpoint filtering will be handled by #1043 (which also has most of the background on this task in it)

**Comment by lamont-granquist** [comment]
(I'm not positive that the second task is that useful or worthwhile, but included it for completeness -- it might actually be useful to still have self-dependencies show up in the GUI so that when knife complains about a self-dependency that user's can see the self-dependency in the GUI and not hide that from users the way that #1043 hides it from berkshelf).

**Comment by nellshamrell** [comment]
@lamont-granquist: going to close this for now, but if you complete further work on it please feel free to re-open it!
