### ISSUE TITLE
Create rails upgrade checklist

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2040]
@skkprogress commented on [Mon Jul 05 2021](https://github.com/chef/chef/issues/11780)

---

@skkprogress commented on [Mon Jul 05 2021](https://github.com/chef/chef/issues/11780#issuecomment-874094200)

- [x] Audit of supermarket and manage repos

- [x] Document detailing what are the broad areas to be focussed on for upgrade

- [x] List of red flags

- [x] Milestones based upgrade plan

**Comment by RajeshPaul38** [comment]
Have worked on the sanity check of the existing testcases. Also created documentation of setting up  test env for supermarket.
https://discourse.chef.io/t/setup-supermarket-test-environment/20097

**Comment by tas50** [comment]
Rails upgrade complete
