### ISSUE TITLE
Setting up dev environment

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2041]
@skkprogress commented on [Mon Jul 05 2021](https://github.com/chef/chef/issues/11779)

---

@skkprogress commented on [Mon Jul 05 2021](https://github.com/chef/chef/issues/11779#issuecomment-874090860)

- [x] Run rails server for Supermarket and Manage on local machine

- [x] Run tests

- [x] Understand (document if needed) release pipeline

- [x] Deployment to non-prod environments

- [x] Simulate using terraforms/or other scripting tools

**Comment by RajeshPaul38** [comment]
Done with dev env setup of chef-supermarket and chef-server. Have also connnected supermarket with oc-id in chef-server.
