### ISSUE TITLE
PG upgrade

### ISSUE THREAD

**Issue by skkprogress** [chef/supermarket#2309]
**Context:** Supermarket is running on an unsupported postgres version. It needs to be upgraded into 13.3
**Acceptance criteria: **

- [ ] Version to be upgraded to 13.3
- [ ] Docs for upgrade to be created
- [ ] Upgrade/migration scripts to be created if needed
- [ ] Real world example for upgrade to be tested with mocked data
- [ ] New scenarios to test dependancies to be added if needed
